# Generated by Django 4.2.7 on 2023-12-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='user',
        ),
    ]
